[package]
name = "wabi_wasmtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wabi_runtime_api = { path = "../api" }

bevy = { version = "0.9.0-dev", default-features = false }

wasmtime = "0.40"